services:
  mysql-maintainer:
    image: ccr.ccs.tencentyun.com/impulsian/mysql-maintainer:latest
    container_name: mysql-maintainer
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - "${SERVER_PORT:-27168}:27168"
    volumes:
      - ./db_backups:/app/db_backups
    restart: unless-stopped
